### PR TITLE
Refactored to use an object model

### PR DESCRIPTION
**Pull request by mindplay-dk**
Refactored to use an object model, avoiding arrays (and array references) and adding annotations for IDE support.

Should be slightly faster in PHP 5.6, and may be slightly slower in older versions - should also be more memory efficient in PHP 5.4 and newer. (I haven't forked/updated the benchmarks)

This of course is a BC break, as it changes the API completely, as reflected by the updated unit-test.

### CODE REVIEW

**Comment by mindplay-dk** [comment]
Benchmark results before and after refactoring:

```
                              BEFORE:            AFTER:
TreeRoute init time:          0.011127948760986  0.0073940753936768 
TreeRoute first route time:   0.17026424407959   0.22758173942566
TreeRoute middle route time:  0.27509617805481   0.27978897094727
TreeRoute last route time:    0.26447415351868   0.27587676048279
TreeRoute not found time:     0.16178870201111   0.1635205745697
```

As expected, init time is slightly faster, first route time is now slightly worse, middle/last route and not-found cases are mostly unchanged.

This is benchmarking with your benchmark with slight adjustments, on my fork, which by now has a whole bunch of other features, as reflected by the [unit test](https://github.com/mindplay-dk/TreeRoute/blob/master/tests/unit/RouterTest.php) - it supports pattern preprocessing, regular expression macros, multiple parameters in a single path part, modular (and lazy) route definitions, and handler dispatch with parameter injection. (most of these features were added to bring it in alignment with my own router, [walkway](https://github.com/mindplay-dk/walkway), which has a somewhat unorthodox API that some have found hard to understand, and is considerably slower than TreeRoute, which is why I'm putting in this work.)

Let me know if you might be interested in merging these changes - if not, I might change the name and package this separately, as there are some major API incompatibilities.

**Comment by baryshev** [comment]
Thanks for PR. I need some time to review and test the changes.

**Comment by mindplay-dk** [comment]
Loads more work has gone into this by now, and we're pretty close to happy with the result. If you're interested, we're faced with [one remaining big decision](https://github.com/mindplay-dk/TreeRoute/blob/master/src/Router.php#L13) - as there was no documentation in the original source code stating what a handler is, I assumed it was a `callable`, but you obviously meant for that to be a string, since closures cannot be serialized, and `getRoutes()` / `setRoutes()` wouldn't work then.

I've outlined the options (three that I can think of) in the TODO referenced above. It's a tough call. I'm meeting with two team members in the morning to try to decide. If you have an opinion, please share. I hope we make the best decision, as this will become the router for our platform probably for the next decade to come :-)

**Comment by mindplay-dk** [comment]
We decided today to switch from handlers being `callable` back to `string` as per your original design, to restore support for caching.

We also decided to drop support for URL creation, as this creates too much complexity - that responsibility has been pushed to an independent (optional) base class for URL creation helpers. 

Also the dispatch responsibility has been extracted and pushed to a separate class, and is also an optional feature - since any convention about turning handler names into callables is going to be pretty heavily opinionated, and since our class-per-action strategy is perhaps somewhat unconventional (but very well founded) we decided not to impose this on anyone else.

You can see our [design notes](https://github.com/mindplay-dk/TreeRoute/#design-notes) at the bottom of the README.

I'm pretty sure this is too far off from your original library by now for it to make sense for you to merge the changes from our fork, but that's up to you of course. We're happy to give our package a different name, or retain the original name, that's up to you, but most likely we will change the package vendor name to differentiate our fork for installation, and likely we will change the namespace as well to avoid collisions. Our fork is not at all compatible with yours, so... :-)

**Comment by mindplay-dk** [comment]
For the record, our fork now has a new package name and namespace, and will be tagged 2.0 later today - the project history is retained, you have been credited at the top of the README, and the fork remains licensed under the same license as your original project.

**Pull request closed without merging**
